# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
#  - name: EmbeddingIntentClassifier
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 3
#  - name: KerasPolicy
#    max_history: 3
#    epochs: 200 # no of times the algorithm will traverse back and forth on training data to build model
#    validation_split: 0.2 # amount of training data used during training. this is like test_train split
#    random_seed: 1 # helps to get reproducible results for the same inputs
  - name: FormPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback' # This is RASA's default fallback action
#  - name: TwoStageFallbackPolicy
#      nlu_threshold: 0.3
#      ambiguity_threshold: 0.1
#      core_threshold: 0.3
#      fallback_core_action_name: 'action_default_fallback' # This is RASA's default fallback action
#      fallback_nlu_action_name: 'action_default_fallback' # This is RASA's default fallback action
#      deny_suggestion_intent_name: "out_of_scope"
  - name: TEDPolicy
    max_history: 5
    epochs: 100

